apiVersion: v1
kind: Secret
metadata:
  name: enable-database-engine-secret
  namespace: enable
type: Opaque
data:
  username: c2E=
  password: U2VjcmV0UGFzc3dvcmQxMjU1
  connection-string: U2VydmVyPWVuYWJsZS1kYXRhYmFzZS1lbmdpbmUtc2VydmljZSwxNDM0O0RhdGFiYXNlPWVuZ2luZS1kYXRhYmFzZTtVc2VyIElkPXNhO1Bhc3N3b3JkPVNlY3JldFBhc3N3b3JkMTI1NTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPXRydWU7