apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: enable-database-engine-pvc
    namespace: enable
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: local-path