version: '3.9'

services:
  enable-registry:
    build:
      context: ./enable-registry
      dockerfile: ./docker/Dockerfile
    container_name: enable-registry
    expose:
      - "8761"
    environment:
      spring.profiles.active: prod

  enable-execution-database:
    image: mysql:8.0.32
    container_name: enable-execution-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'executiondb'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - "3306:3306"
    volumes:
      - db_data_execution:/var/lib/mysql

  enable-execution-service:
    build:
      context: ./enable-execution-service
      dockerfile: ./docker/Dockerfile
    container_name: enable-execution-service
    restart: unless-stopped
    expose:
      - "8762"
    depends_on:
      - enable-registry
      - enable-execution-database
    environment:
      spring.profiles.active: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://enable-execution-database:3306/executiondb?useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: secret
      EUREKA_SERVER: http://enable-registry:8761/eureka

#  enable-design-frontend:
#    build:
#      context: ./enable-design-frontend
#      dockerfile: ./docker/Dockerfile
#    container_name: enable-design-frontend
#    ports:
#      - "80:8080"
#    environment:
#      ENABLE_API_GATEWAY_BASEURL: "http://enable-execution-service:8080"

  enable-api-gateway:
    build:
      context: ./enable-api-gateway
      dockerfile: ./docker/Dockerfile
    container_name: enable-api-gateway
    ports:
      - "127.0.0.1:8080:8760"
    depends_on:
      - enable-registry
      - enable-execution-service
    environment:
      spring.profiles.active: prod
      EUREKA_SERVER: http://enable-registry:8761/eureka


volumes:
  db_data_execution: