apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enable-gateway-ingress
  namespace: enable
spec:
  rules:
  - host: gateway.localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: enable-gateway-service
            port:
              number: 8080