apiVersion: v1
kind: Secret
metadata:
  name: enable-database-execution-secret
  namespace: enable
type: Opaque
data:
  connection-string: U2VydmVyPXRjcDplbmFibGUtZGF0YWJhc2UtZXhlY3V0aW9uLXNlcnZpY2UuZGF0YWJhc2Uud2luZG93cy5uZXQsMTQzMztJbml0aWFsIENhdGFsb2c9ZXhlY3V0aW9uLWRhdGFiYXNlO1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPVNlY3JldFVzZXIxMjU1O1Bhc3N3b3JkPVNlY3JldFBhc3N3b3JkMTI1NTtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOw==