apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-grafana-deployment
  namespace: enable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-grafana
  template:
    metadata:
      labels:
        app: monitoring-grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: monitoring-grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - name: monitoring-grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: monitoring-grafana-data
          persistentVolumeClaim:
            claimName: monitoring-grafana-pvc