apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana-service
  namespace: enable
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: monitoring-grafana
  type: LoadBalancer