# Variables
#  ENABLE_USER_SERVICE_BASEURL: ${ENABLE_USER_SERVICE_BASEURL}
#  ENABLE_EXECUTION_SERVICE_BASEURL: ${ENABLE_EXECUTION_SERVICE_BASEURL}

server:
  port: 8760
  #spring.main.allow-bean-definition-overriding: true
  #spring.main.web-application-type: reactive

spring:
  application:
    name: enable-api-gateway
  cloud:
    gateway:
      routes:
        - id: enable-execution-service
          uri: lb://enable-execution-service/api
          predicates:
            - Path=/execution/**
        - id: enable-registry
          uri: lb://enable-registry
          predicates:
            - Path=/enable-registry/**
          filters:
            - StripPrefix=1
        - id: registry
          uri: lb://enable-registry
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://enable-registry
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info





