name: main

on:
    push:
        branches: [ "main", "master" ]
    pull_request:
        branches: [ "main", "master" ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Azure
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Get AKS credentials
              run: az aks get-credentials --resource-group enableAKSResourceGroupEastUS --name enable

            - name: Apply Kubernetes namespace manifest
              run: |
                kubectl apply -f ./infrastructure/kubernetes/.

            - name: Create/ Update Kubernetes Secret
              run: |
                echo "apiVersion: v1
                kind: Secret
                metadata:
                  name: enable-database-auth-secret
                  namespace: enable
                type: Opaque
                stringData:
                  connection-string: '${{ secrets.DB_AUTH_CONNECTION_STRING }}'" | kubectl apply -f -
              
            - name: Create/ Update Kubernetes Secret
              run: |
                echo "apiVersion: v1
                kind: Secret
                metadata:
                  name: enable-database-execution-secret
                  namespace: enable
                type: Opaque
                stringData:
                  connection-string: '${{ secrets.DB_EXECUTION_CONNECTION_STRING }}'" | kubectl apply -f -
            
            - name: Create/ Update Kubernetes Secret
              run: |
                echo "apiVersion: v1
                kind: Secret
                metadata:
                  name: enable-database-process-secret
                  namespace: enable
                type: Opaque
                stringData:
                  connection-string: '${{ secrets.DB_PROCESS_CONNECTION_STRING }}'" | kubectl apply -f -
            
            - name: Create/ Update Kubernetes Secret
              run: |
                echo "apiVersion: v1
                kind: Secret
                metadata:
                  name: enable-gateway-secret
                  namespace: enable
                type: Opaque
                stringData:
                  key-alias: '${{ secrets.GATEWAY_KEY_ALIAS }}'
                  key-store-password: '${{ secrets.GATEWAY_KEY_STORE_PASSWORD }}'" | kubectl apply -f -
            
            - name: Create/ Update Kubernetes Secret
              run: |
                echo "apiVersion: v1
                kind: Secret
                metadata:
                  name: enable-rabbitmq-secret
                  namespace: enable
                type: Opaque
                stringData:
                  username: '${{ secrets.RABBITMQ_USERNAME }}'
                  password: '${{ secrets.RABBITMQ_PASSWORD }}'" | kubectl apply -f -
            
            - name: Create/ Update Kubernetes Secret
              run: |
                echo "apiVersion: v1
                kind: Secret
                metadata:
                  name: enable-service-api-auth-secret
                  namespace: enable
                type: Opaque
                stringData:
                  jwt-key: '${{ secrets.SERVICE_AUTH_JWT_KEY }}'
                  jwt-issuer: '${{ secrets.SERVICE_AUTH_JWT_ISSUER }}'
                  jwt-audience: '${{ secrets.SERVICE_AUTH_JWT_AUDIENCE }}'" | kubectl apply -f -
            
            - name: Create/ Update Kubernetes Secret
              run: |
                echo "apiVersion: v1
                kind: Secret
                metadata:
                  name: enable-service-encryption-secret
                  namespace: enable
                type: Opaque
                stringData:
                  encryption-key: '${{ secrets.SERVICE_ENCRYPTION_KEY }}'" | kubectl apply -f -

            - name: Apply Kubernetes manifests
              run: |
                kubectl apply -f ./infrastructure/kubernetes/enable-gateway/.
                kubectl apply -f ./infrastructure/kubernetes/enable-registry/.
                kubectl apply -f ./infrastructure/kubernetes/enable-rabbitmq/.
                kubectl apply -f ./infrastructure/kubernetes/enable-service-api-auth/.
                kubectl apply -f ./infrastructure/kubernetes/enable-service-api-execution/.
                kubectl apply -f ./infrastructure/kubernetes/enable-service-api-process/.
                kubectl apply -f ./infrastructure/kubernetes/enable-webapp-management/.
